# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('soundcloud', 'SoundCloud')], default='youtube', max_length=45),
        ),
    ]
