# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('regarding', models.CharField(choices=[('None', 'none'), ('none', None), ('events', 'Events'), ('promo', 'Promotion'), ('endorse', 'Endorsement'), ('collab', 'Collaboration')], max_length=15)),
                ('message', models.TextField()),
            ],
        ),
    ]
