# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactformdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
