# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170509_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/gallery/')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
